[2021-08-11 10:44:11,904] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-11 10:44:11,910] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-11 10:44:11,910] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-11 10:44:11,910] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-11 10:44:11,910] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-11 10:44:11,915] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): also_run_this> on 2021-08-09T00:00:00+00:00
[2021-08-11 10:44:11,917] {standard_task_runner.py:52} INFO - Started process 69394 to run task
[2021-08-11 10:44:11,923] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2021-08-09T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', '/Users/Alex/.local/share/virtualenvs/airflow-1c5-bq0J/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/var/folders/t_/pcbjm7w572gbxhwznsq7tq8r0000gn/T/tmpzdhnwkm9', '--error-file', '/var/folders/t_/pcbjm7w572gbxhwznsq7tq8r0000gn/T/tmpefy0vtlp']
[2021-08-11 10:44:11,926] {standard_task_runner.py:77} INFO - Job 5: Subtask also_run_this
[2021-08-11 10:44:11,962] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.also_run_this 2021-08-09T00:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-08-11 10:44:11,992] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-08-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-09T00:00:00+00:00
[2021-08-11 10:44:11,993] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/t_/pcbjm7w572gbxhwznsq7tq8r0000gn/T
[2021-08-11 10:44:11,994] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo "run_id=scheduled__2021-08-09T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-08-09 00:00:00+00:00: scheduled__2021-08-09T00:00:00+00:00, externally triggered: False>"']
[2021-08-11 10:44:11,999] {subprocess.py:74} INFO - Output:
[2021-08-11 10:44:12,002] {subprocess.py:78} INFO - run_id=scheduled__2021-08-09T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-08-09 00:00:00+00:00: scheduled__2021-08-09T00:00:00+00:00, externally triggered: False>
[2021-08-11 10:44:12,002] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-11 10:44:12,014] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20210809T000000, start_date=20210811T144411, end_date=20210811T144412
[2021-08-11 10:44:12,028] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-11 10:44:12,059] {local_task_job.py:149} INFO - Task exited with return code 0
